=== umbe77/uStateMachine/Schema/state-machine.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "id": "/state-machine",
    "description": "State Machine Schema Definition",
    "title": "StateMachine",
    "properties": {
        "name": {
            "type": "string"
        },
        "version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "states": {
            "type": "object",
            "patternProperties": {
                "^\\w+$": {
                    "$ref": "/state"
                }
            },
            "additionalProperties": false
        },
        "initial": {
            "type": "string",
            "pattern": "^\\w+$"
        }
    },
    "required": ["name", "version", "states", "initial"],
    "additionalProperties": false
}

=== umbe77/uStateMachine/test/persistance/statemachines/firstwf.json
{
    "name": "FirstWF",
    "version": "1.0.0",
    "states": {
        "PreOrder": {
            "name": "PreOrder",
            "transitions": {
                "InOrder": {
                    "destination": "InOrder"
                },
                "OrderSent": {
                    "destination": "OrderSent"
                }
            }
        },
        "InOrder": {
            "name": "InOrder",
            "transitions": {
                "OrderSent": {
                    "destination": "OrderSent"
                }
            }
        },
        "OrderSent": {
            "name": "OrderSent",
            "transitions": {}
        }
    },
    "initial": "PreOrder"
}
